/**
 * Common Ethiopian name mappings: English -> Amharic
 * Based on common transliteration patterns
 */

export const COMMON_NAMES: Record<string, string> = {
  'amanuel': 'አማኑኤል',
  'tadesse': 'ታደሰ',
  'gebre': 'ገብሬ',
  'bekele': 'በቀለ',
  'selam': 'ሰላም',
  'mekonnen': 'መኮንን',
  'abebe': 'አበበ',
  'tesfaye': 'ተስፋዬ',
  'meron': 'መሮን',
  'addis': 'አዲስ',
  'yohannes': 'ዮሐንስ',
  'mulugeta': 'ሙሉጌታ',
  'alemayehu': 'አለማየሁ',
  'getachew': 'ጌታቸው',
  'zewdu': 'ዘውዱ',
  'tigist': 'ጥግስት',
  'marta': 'ማርታ',
  'hanna': 'ሐና',
  'mariam': 'ማርያም',
  'helen': 'ሄለን',
  'dawit': 'ዳዊት',
  'solomon': 'ሰሎሞን',
  'daniel': 'ዳንኤል',
  'michael': 'ሚካኤል',
  'samuel': 'ሳሙኤል',
  'joseph': 'ዮሴፍ',
  'david': 'ዳዊት',
  'john': 'ዮሐንስ',
  'paul': 'ጳውሎስ',
  'peter': 'ጴጥሮስ',
  'mark': 'ማርቆስ',
  'luke': 'ሉቃስ',
  'matthew': 'ማቴዎስ',
  'james': 'ያዕቆብ',
  'thomas': 'ቶማስ',
  'andrew': 'አንድሬያስ',
  'philip': 'ፊሊጶስ',
  'bartholomew': 'በርተሎሜዎስ',
  'matthias': 'ማትታይያስ',
  'simon': 'ስምዖን',
  'jude': 'ይሁዳ',
  'judas': 'ይሁዳ',
  'mary': 'ማርያም',
  'elizabeth': 'ኤልሳቤጥ',
  'anna': 'አና',
  'sarah': 'ሳራ',
  'rebecca': 'ሬቤካ',
  'rachel': 'ራኤል',
  'leah': 'ሊያ',
  'deborah': 'ዴቦራ',
  'ruth': 'ሩት',
  'esther': 'አስቴር',
  'judith': 'ይሁዲት',
  'susanna': 'ሱሳና',
  'salome': 'ሳሎሜ',
  'joanna': 'ዮአና',
  'phoebe': 'ፎይቤ',
  'priscilla': 'ፕሪስኪላ',
  'aquila': 'አኩይላ',
  'apollos': 'አጶሎስ',
  'barnabas': 'በርናባስ',
  'silas': 'ሲላስ',
  'timothy': 'ጢሞቴዎስ',
  'titus': 'ጢቶስ',
  'philemon': 'ፊልሞን',
};
